postsubmits:
  dafiti-group/prow-plugins:
  - name: prow-job-test
    always_run: true
    decorate: true
    spec:
      containers:
      - image: alpine:latest
        command:
        - echo "teste"
