apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prow

resources:
- ns.yaml
- deployment.yaml
- service.yaml
- config.yaml
- secrets.yaml

secretGenerator:
- name: github-token
  # env is a path to a file to read lines of key=val
  # you can only specify one env file per secret.
  env: ./secrets/env
  type: Opaque
