apiVersion: v1
kind: Service
metadata:
  name: prow-plugins
  namespace: prow
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: prow-plugins
  type: NodePort